# fly.toml app configuration file generated for practice9 on 2023-11-12T20:25:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "practice9"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
