GET HTTP://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/655006116bdede2bdf6ed9ca

###
DELETE http://localhost:3001/api/notes/65455056cc67b944bbab8197

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Oth",
  "important": true
}

###
PUT http://localhost:3001/api/notes/655006116bdede2bdf6ed9ca
Content-Type: application/json

{
  "content": "Other update test2 content is available106",
  "important": false
}