GET HTTP://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/1

###
DELETE http://localhost:3001/api/notes/65439742c4c391a09ade61fb

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Other content is available77",
  "important": true
}

###
PUT http://localhost:3001/api/notes/6543972dc4c391a09ade61f9
Content-Type: application/json

{
  "content": "Other test content is available2",
  "important": false
}